### ISSUE TITLE
po dodaniu nowego modułu nie jest on widoczny w "processing systems"

### ISSUE THREAD

**Issue by olaf89** [jarep/msom#33]

**Comment by jarep** [comment]
a w jaki sposób udało Ci się dodać nowy moduł? bo z tego co wiem to nie jest zaimplementowane...

**Comment by olaf89** [comment]
tzn chodziło mi o Model, pomylka

**Comment by jarep** [comment]
chyba, że mówisz o modelach. W takim przypadku trzeba uważać żeby nie nadpisać lokalnej pamięci, gdy np jakiś model jest w trakcie symulacji - bo dane symulacji nie są zapisywane w bazie

**Comment by jarep** [comment]
popatrzę na to, bo właśnie rozbudowuję tą cześć.

**Comment by olaf89** [comment]
ok, zrobiłem PR jak coś to możesz zobaczyć czy to ma sens

**Comment by olaf89** [comment]
jak dla mnie za kazdym razem gdy pobieramy liste, powinno być odświeżone natomiast gdy juz mamy ID to znaczy ze lista jest pewnie aktualna,

**Comment by jarep** [comment]
OK, popatrzę na PR zaraz, narazie mam nie zacomitowane zmiany lokalne, więc jak skończę do wrócę do tego
